import { Pin } from "@/types";

export const seedPins: Pin[] = [
  {
    id: "pin-1",
    title: "Google Colab CLI",
    description: "Run Colab notebooks from the terminal. GPU access without the browser.",
    url: "https://colab.research.google.com",
    tags: ["tools", "ai", "gpu"],
    notes: "",
    x: 100,
    y: 100,
    createdAt: new Date().toISOString(),
  },
  {
    id: "pin-2",
    title: "Wayve",
    description: "Self-driving cars powered by AI. London-based, great engineering blog.",
    url: "https://wayve.ai",
    tags: ["career", "robotics", "explore"],
    notes: "",
    x: 400,
    y: 150,
    createdAt: new Date().toISOString(),
  },
  {
    id: "pin-3",
    title: "Edinburgh MSc AI",
    description: "MSc in Artificial Intelligence at the University of Edinburgh.",
    url: "https://www.ed.ac.uk/informatics/postgraduate/degrees/msc-ai",
    tags: ["education", "career"],
    notes: "",
    x: 200,
    y: 400,
    createdAt: new Date().toISOString(),
  },
  {
    id: "pin-4",
    title: "Visual Context Compression",
    description: "Research on compressing visual context for efficient multi-modal learning.",
    url: "",
    tags: ["research", "dissertation", "explore"],
    notes: "",
    x: 500,
    y: 350,
    createdAt: new Date().toISOString(),
  },
  {
    id: "pin-5",
    title: "Edoardo Ponti",
    description: "Professor at Edinburgh, works on NLP and efficient transformers.",
    url: "https://www.ed.ac.uk/profile/edoardo-ponti",
    tags: ["professor", "edinburgh"],
    notes: "",
    x: 700,
    y: 200,
    createdAt: new Date().toISOString(),
  },
];
